// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uemoekuuaqspkweiupkw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVlbW9la3V1YXFzcGt3ZWl1cGt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NjYxNTYsImV4cCI6MjA2MDU0MjE1Nn0.bR-bBBeffqpcnfQ4mJyO7AOUI03auRaYQkr2kRFEU6Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);